### ISSUE TITLE
Broken with Ruby 2.4.2

### ISSUE THREAD

**Issue by gnomus** [lolcommits/lolcommits-slack#2]
It seems like this Plugin is broken if you use ruby 2.4.2

```
$ lolcommits -c
*** Preserving this moment in history.
Posting to Slack ... failed! key not found: :ciphers - retrying ...
Posting to Slack ... failed! key not found: :ciphers - giving up ...
Try running config again:
	lolcommits --config --p slack
```
With ruby 2.3.3 and the same config everything works :)

I could track this back to the rest-client dependency
https://github.com/rest-client/rest-client/issues/569

According to this comment
https://github.com/lolcommits/lolcommits-slack/blob/master/lolcommits-slack.gemspec#L37
we are limited by the yammer Plugin but since it was moved to a seperate gem 20 Days ago this error might be fixable.

**Comment by matthutchinson** [comment]
That's odd, since Travis is reporting a [green build](https://travis-ci.org/lolcommits/lolcommits-slack) for Ruby 2.4.2.. But you're right - I'm in the process of converting all plugins to gems and updating dependencies.  I'll be releasing a new version of lolcommits very soon, with everything extracted - so if this is a real issue it should go away soon.

**Comment by matthutchinson** [comment]
This should be fixed now, with the latest release of lolcommits `0.9.8` and this plugin `0.0.2`
